"""Synthetic building-condition profile generator for PPO-2.

This module generates exogenous hourly profiles only:
outdoor temperature, occupancy, electricity price, and comfort setpoint.
Indoor temperature and HVAC energy are generated by the building environment.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

import numpy as np
import pandas as pd


@dataclass(frozen=True)
class ProfileConfig:
    """Configuration for synthetic daily building profiles."""

    episode_hours: int = 24
    base_outdoor_temp_c: float = 27.0
    outdoor_amplitude_c: float = 4.5
    outdoor_noise_std_c: float = 0.6

    comfort_setpoint_c: float = 22.0

    base_price: float = 0.50
    peak_price: float = 1.00
    price_noise_std: float = 0.04

    occupancy_noise_std: float = 0.04


def _daily_temperature(
    hours: np.ndarray,
    rng: np.random.Generator,
    cfg: ProfileConfig,
) -> np.ndarray:
    """Generate a smooth daily outdoor-temperature profile."""
    # Peak temperature occurs around 15:00.
    phase = 2 * np.pi * (hours - 15) / 24
    day_offset = rng.normal(0.0, 1.0)
    amplitude = max(1.0, cfg.outdoor_amplitude_c + rng.normal(0.0, 0.6))

    temp = (
        cfg.base_outdoor_temp_c
        + day_offset
        + amplitude * np.cos(phase)
        + rng.normal(0.0, cfg.outdoor_noise_std_c, size=len(hours))
    )
    return temp


def _occupancy_profile(
    hours: np.ndarray,
    rng: np.random.Generator,
    cfg: ProfileConfig,
) -> np.ndarray:
    """Generate a normalized office/classroom-like occupancy profile."""
    occupancy = np.zeros(len(hours), dtype=float)

    # Gradual arrival, high daytime occupancy, gradual departure.
    for i, hour in enumerate(hours):
        if 7 <= hour < 9:
            occupancy[i] = 0.25 + 0.35 * (hour - 7)
        elif 9 <= hour < 17:
            occupancy[i] = 0.80
        elif 17 <= hour < 20:
            occupancy[i] = 0.55 - 0.18 * (hour - 17)
        else:
            occupancy[i] = 0.03

    occupancy += rng.normal(0.0, cfg.occupancy_noise_std, size=len(hours))
    return np.clip(occupancy, 0.0, 1.0)


def _electricity_price(
    hours: np.ndarray,
    rng: np.random.Generator,
    cfg: ProfileConfig,
) -> np.ndarray:
    """Generate a simple time-varying electricity-price profile."""
    price = np.full(len(hours), cfg.base_price, dtype=float)

    # Morning shoulder.
    morning = (hours >= 7) & (hours < 10)
    price[morning] = 0.70

    # Daytime.
    daytime = (hours >= 10) & (hours < 16)
    price[daytime] = 0.82

    # Evening peak.
    evening = (hours >= 16) & (hours < 20)
    price[evening] = cfg.peak_price

    price += rng.normal(0.0, cfg.price_noise_std, size=len(hours))
    return np.clip(price, 0.05, None)


def generate_daily_profile(
    seed: int,
    config: ProfileConfig | None = None,
    profile_id: str | int = "day_0001",
) -> pd.DataFrame:
    """Generate one reproducible 24-hour synthetic building profile."""
    cfg = config or ProfileConfig()

    if cfg.episode_hours != 24:
        raise ValueError("PPO-2 v1.0 currently requires 24 hourly steps per episode.")

    rng = np.random.default_rng(seed)
    hours = np.arange(cfg.episode_hours)

    profile = pd.DataFrame(
        {
            "profile_id": str(profile_id),
            "hour": hours,
            "outdoor_temp_c": _daily_temperature(hours, rng, cfg),
            "occupancy": _occupancy_profile(hours, rng, cfg),
            "electricity_price": _electricity_price(hours, rng, cfg),
            "comfort_setpoint_c": cfg.comfort_setpoint_c,
        }
    )

    return profile


def generate_profiles(
    n_profiles: int,
    seed: int,
    split: Literal["train", "validation", "test"],
    config: ProfileConfig | None = None,
) -> pd.DataFrame:
    """Generate a collection of daily profiles as one long DataFrame."""
    if n_profiles <= 0:
        raise ValueError("n_profiles must be positive.")

    cfg = config or ProfileConfig()
    master_rng = np.random.default_rng(seed)

    frames = []
    for idx in range(n_profiles):
        day_seed = int(master_rng.integers(0, 2**32 - 1))
        profile_id = f"{split}_day_{idx + 1:04d}"

        day = generate_daily_profile(
            seed=day_seed,
            config=cfg,
            profile_id=profile_id,
        )
        day["split"] = split
        frames.append(day)

    return pd.concat(frames, ignore_index=True)


def validate_profiles(profiles: pd.DataFrame) -> dict:
    """Run structural and range checks on generated profiles."""
    required = {
        "profile_id",
        "hour",
        "outdoor_temp_c",
        "occupancy",
        "electricity_price",
        "comfort_setpoint_c",
    }

    missing = sorted(required - set(profiles.columns))
    if missing:
        raise ValueError(f"Missing required columns: {missing}")

    rows_per_profile = profiles.groupby("profile_id").size()
    checks = {
        "no_missing_values": not profiles[list(required)].isna().any().any(),
        "hour_range_valid": profiles["hour"].between(0, 23).all(),
        "occupancy_range_valid": profiles["occupancy"].between(0, 1).all(),
        "price_nonnegative": (profiles["electricity_price"] >= 0).all(),
        "one_day_per_profile": (rows_per_profile == 24).all(),
        "profile_count": int(profiles["profile_id"].nunique()),
        "row_count": int(len(profiles)),
    }

    checks["all_checks_passed"] = all(
        value is True for key, value in checks.items()
        if key not in {"profile_count", "row_count"}
    )
    return checks


if __name__ == "__main__":
    demo = generate_profiles(
        n_profiles=3,
        seed=2026,
        split="train",
    )
    print(demo.head())
    print(validate_profiles(demo))
